# Generated by Django 4.0.6 on 2022-07-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='video')),
                ('video_240', models.FileField(blank=True, null=True, upload_to='video_240')),
                ('video_360', models.FileField(blank=True, null=True, upload_to='video_360')),
                ('time_to_convert', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
