# Generated by Django 4.0.6 on 2023-03-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_alter_video_video_240_alter_video_video_360'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_240',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_360',
        ),
        migrations.AddField(
            model_name='video',
            name='url_240p',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='url_360p',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='time_to_convert',
            field=models.FloatField(default=0),
        ),
    ]
